### PR TITLE
adding ALPACA docs

### PR DESCRIPTION
**Pull request by agporto**

### CODE REVIEW

**Comment by muratmaga** [comment]
Can you edit the ALPACA.py as well to point out to the the online tutorial. This section

https://github.com/SlicerMorph/SlicerMorph/blob/1bbfd33e531d61e0e21d1ec70ecc2f30d43f8096/ALPACA/ALPACA.py#L29-L40

**Comment by agporto** [comment]
Do you mean adding that there is an online tutorial at 'https://github.com/SlicerMorph/S_2020/tree/master/Lab_ALPACA' on the self.parent.helpText section?

**Comment by muratmaga** [comment]
Yes, and also comment the defaultHelpLink function (or whatever it is called) that points out to wiki

**Comment by agporto** [comment]
I will close this one and submit another.

**Pull request closed without merging**
