### PR TITLE
Improve ImageStacks

### PR DESCRIPTION
**Pull request by lassoan**
I've attended this training yesterday - https://twitter.com/MorphoFun/status/1363209209307942915. The training still used ImageJ for image stack conversion to nrrd, because somehow ImageStacks was not convincing enough. These changes intend to make the module easier to use (support application-wide drag-and-drop and make things simpler).

- Allow loading images into ImageStacks by drag-and-dropping files/folders to the application window. "Load files using ImageStacks module" option is offered if at least one of the files is a jpg/tif/png/bmp. If a single file is selected then it is used as archetype, if multiple files are found then they are all added to the file list.
- Initialize spacing from value stored in the first file.
- Show wait cursor while loading the volume.
- Make Full and Downsampled volume size information display more compact.
- Make widget layout and nomenclature simpler and more consistent ("filename pattern" instead of "archetype", always use "Browse" word for browsing files, add "..." to buttons that open a popup, replace "None" text in output node selector by "(Create new volume)" as it actually creates a new output volume, etc.)

### CODE REVIEW

**Review by pieper — APPROVED** [review]
LGTM 👍 

@muratmaga do you want to try these?  Merge if you have no comments.

**Comment by lassoan** [comment]
See demo here:

https://youtu.be/tjZUOqnrc_Y

**Comment by muratmaga** [comment]
@lassoan thank you for this. 
That particular group has been using Slicer longer than ImageStack has been around. I do not think Fiji is offering anything more convenient than what ImageStacks provide even without your modifications. I suspect it is more of an inertia than anything else. 

Anyways, these look great changes. My only concern is guessing the image spacing from the file, which is usually incorrectly set in 2D formats. Let me try first.

Thanks again.

**Comment by muratmaga** [comment]
@lassoan @pieper 
this looks great. 

It looks like directory parsing (i.e., dragging and dropping a folder) has some issues. I am trying with the sample data we bundle with SlicerMorph, which is here https://github.com/SlicerMorph/SampleData/blob/master/sample_Skyscan_mCT_reconstruction.zip

People might have very confusing directory structures and file contents. So my suggestion would be actually disable that. Drag and dropping one sample file is simple enough.
 
```
Traceback (most recent call last):
  File "C:/Users/amaga/AppData/Local/NA-MIC/Slicer 4.13.0-2021-02-17/NA-MIC/Extensions-29718/SlicerMorph/lib/Slicer-4.13/qt-scripted-modules/ImageStacks.py", line 311, in onLoadButton
    outputNode = self.logic.loadByPaths(paths, self.currentNode(), properties)
  File "C:/Users/amaga/AppData/Local/NA-MIC/Slicer 4.13.0-2021-02-17/NA-MIC/Extensions-29718/SlicerMorph/lib/Slicer-4.13/qt-scripted-modules/ImageStacks.py", line 474, in loadByPaths
    volumeArray[sliceIndex] = sliceArray
ValueError: could not broadcast input array from shape (668,1000) into shape (444,444)
```

**Comment by lassoan** [comment]
> Anyways, these look great changes. My only concern is guessing the image spacing from the file, which is usually incorrectly set in 2D formats. Let me try first.

We already use this XY spacing (even without asking the user) when we load the image using Add data dialog. This module displays the spacing and allows the user to change it, so the risk of using wrong spacing value for XY is greatly reduced.

Images often have isotropic spacing, so using the XY spacing for Z is a reasonable guess. The previous default of 1.0 was a potentially misleading value as well. If you really wanted to make sure the user explicitly specified a z value then you should have set the default to an invalid value (such as 0.0 or -1).

**Comment by muratmaga** [comment]
> 
> 
> > Anyways, these look great changes. My only concern is guessing the image spacing from the file, which is usually incorrectly set in 2D formats. Let me try first.
> 
> We already use this XY spacing (even without asking the user) when we load the image using Add data dialog. This module displays the spacing and allows the user to change it, so the risk of using wrong spacing value for XY is greatly reduced.
> 
> Images often have isotropic spacing, so using the XY spacing for Z is a reasonable guess. The previous default of 1.0 was a potentially misleading value as well. If you really wanted to make sure the user explicitly specified a z value then you should have set the default to an invalid value (such as 0.0 or -1).

I agree current behavior is better than what it was before. We always ask them to cross-reference it to the value reported by MorphoSource (or whatever the log file provides) anyways.

So the only remaining issue is the directory parsing that I mentioned above. Otherwise it is great.

**Comment by lassoan** [comment]
> People might have very confusing directory structures and file contents. So my suggestion would be actually disable that. Drag and dropping one sample file is simple enough.

When you drag-and-drop a directory then files in that folder are considered and not the one in subfolders. You can load a single volume from multiple folders by drag-and-dropping all folders at once. This is a behavior that is simple, easy to explain, there is no risk that a large directory traversal will take a long time, and it already works well for many cases. But if you find that storage of a single volume across several folders is very common then we can enable recursive collection of files from all subfolders.

In general, user experience is better if the software works along assumptions that are most likely correct (and reports any errors or warnings if inconsistencies are found) instead of asking the user in advance or outright not do what the user wants. The only exception if there is a safety risk, but since the images are stored in a 2D image stack, we already know that the user is not concerned about safety.

**Comment by muratmaga** [comment]
> When you drag-and-drop a directory then files in that folder are considered and not the one in subfolders. You can load a single volume from multiple folders by drag-and-dropping all folders at once.

Apologies for not being clear. I didn't mean that subfolders may complicate things. It is the files within the folder may have confusing structure. For example in that sample zip file, you will see there is a single bmp file which is actually a shadow image of the specimen and has a different dimension and should not be part of the selection. 
Because of that ImageStacks is not functioning, it is throwing the error I put out. 

This is not our doing, this is how Bruker/Skyscan outputs. Since, it is hard to know what other vendors might be doing (imagine having an identical prefix but two sequences with tiff and jpg extension in the same folder. Former being the shadow image sequence, jpg being the cross-sections derived from them).

**Comment by lassoan** [comment]
Thanks for the clarificiation.

I think it is a good behavior that a folder can be loaded if all image files in it belong to a single series and loading fails if there is a mix of different images. We just need to make sure to display a meaningful error message instead of a silent error in the Python console. What about displaying an error popup:

    Load failed: not all selected files have the same size.

Details (appears when user clicks "Details..." button):

    xyz.bmp size is 123 x 456.
    abc.jpg size is 111x222

**Comment by muratmaga** [comment]
But then what are we expecting  the user going to do with that information? Move those files out of the folder manually?
I still think just dragging a single file is an easier solution.

**Comment by lassoan** [comment]
We could make this a warning only (use the image size of the first file) or add to the error message: "Try to select a single file or specify file pattern."

**Comment by muratmaga** [comment]
If you are inclined about leaving the directory option in place, yes than please add the something like 
"There are multiple datasets in the folder.
xyz.bmp size is 123 x 456.
abc.jpg size is 111x222
Please select a single file as a sample or specify a pattern"

This should however not just print to the log or python window (which most new users don't look), but should appear in the ImageStacks module.

**Comment by lassoan** [comment]
Sounds good, I'll send an updated pull request in a few minutes.

**Comment by lassoan** [comment]
Updated the pull request with reporting of inconsistent frame size:

image

image

**Comment by muratmaga** [comment]
Thank you Andras. Much appreciated.

**Pull request merged**
