### PR TITLE
recognize when nrrd file is being loaded

### PR DESCRIPTION
**Pull request by jmhuie**
Make it so that when users drag and drop .nrrd files into the scene, they will be given the option to open it with the ImageStacks module

### CODE REVIEW

**Comment by muratmaga** [comment]
@jmhuie thanks for the contribution, but I am not sure why anyone would want to use the ImageStacks to load NRRD. That can be directly loaded into the Slicer, and any operation ImageStacks supports, can be done directly using the existing modules.

What's the use case here?

**Comment by jmhuie** [comment]
The biggest benefit of ImageStacks is the ability to load in a low res volume, draw an ROI, and then load in that portion only at high-res. It's far faster than loading in the entire full resolution volume and then cropping it using CropVolume.

This benefit still applies to large nrrd files. We've talked about how nrrd files are a better storage format than a folder of images. However, loading in large nrrd files and cropping them with CropVolume is still painstaking if you try to use the 3D viewer to draw the ROI. It may be impossible on Macs with the Apple Chips given the hardware limitations. That is why Andras added the ability to load a nrrd file through ImageStacks.

There's a possible use cases when segmenting a large "fish burrito" and saving files for each isolated individuals. Since Slicer does not support exporting volumes as an image stack, you're forced to save as a nrrd (I'm in that situation now). Although, the edit I made is just a "quality of life" change that makes it so you don't have to navigate to ImageStacks, click Browse, navigate to the file, etc. 

I guess I could see how this change would potentially confuse general users so I'll defer to you about whether you accept this change.

**Comment by muratmaga** [comment]
I see. The intention is to use ImageStacks for very large NRRD that has potentially multiple elements. The questions then how is that NRRD is created in the first place? Anyways, I can see the use-case, while it does have the potential to confuse people, it is a fairly corner case with potentially a small number of people. 

I can merge this, but can you make sure you add the nhdr extension as well (same thing with NRRD, with a detached header).

**Comment by jmhuie** [comment]
Great, just to add: In my cases, big nrrds are made when isolating individuals from a larger scans but if there's a push to store and share CT scans as nrrd files instead of zipped image stacks (via MorphoSource or otherwise), I could see large nrrds becoming more commonplace.

**Comment by jmhuie** [comment]
I was able to repeat 1.

Not sure what you mean by 2. If I drag and drop an uncompressed or compressed NRRD, the pop up window asking if I want to use the ImageStacks module works (the compressed NRRD won't load in obviously).

**Comment by lassoan** [comment]
Yes, the loading from NRRD module should be fixed: `originalVolumeIJKToRAS` should be read from the NRRD file header.

**Comment by lassoan** [comment]
NRRD reading is very useful, because it enables very weak computers to work with huge images. For example, you have a 20GB mouse scan, but you are actually only interested in the wrist joint, which is a small region, maybe 200MB size. With the NRRD reader the weak computer can load the entire image at low resolution in seconds, select the wrist region, and load that image region at full resolution in seconds. It was possible to do this already on TIFF stacks, but we want everyone to stop using TIFF stacks.

**Pull request merged**
